# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            jwt: ~
            # Configure your JWT settings if required

